### ISSUE TITLE
request status component

### ISSUE THREAD

**Issue by liorkesos** [linnovate/dfa#3]
createrequest status react component that connects to the daml endpoint and displays requests in 3 views
list , calendar/schedule, map
uae danl/react to create  a component that can live out of the default gui

**Comment by liorkesos** [comment]
Hi We'll need a ui/state to show all active requests (hmm requests need statuses and will probably have a lifecycle)

**Comment by donno2048** [comment]
For simple a `status` for `Request`-s we need some very small changes
<details>
<summary>Changes</summary>

Add `status: Text` after [line 34](https://github.com/linnovate/dfa/blob/main/daml/User.daml#L34) and add `, status = "Sent"` at the end of [line 29](https://github.com/linnovate/dfa/blob/main/daml/User.daml#L29) and change [line 9 of requests](https://github.com/linnovate/dfa/blob/main/ui/src/components/Requests.tsx#L9) to `const {sender, receiver, content, status} = request.payload;` and add `<strong>Status: {status}</strong>` after [line 13](https://github.com/linnovate/dfa/blob/main/ui/src/components/Requests.tsx#L13)
</details>

Adding more details will be similar, I understand we want to add `status` (e.g. "pending", "sent", "accepted", …), `geo` (On a map with pins), and `id` (i.e. by the order of sending)

It requires a lot of React implementation I would rather wait with until #7 and #8 are either accepted or rejected so I know which branch to work on.

**Comment by liorkesos** [comment]
Please contrinue with this on main ( I merged Gal ronen's damlchanges)

**Comment by liorkesos** [comment]
Basically I think there should be 3 components showing the same data.

- [x] List request component
     Pretty much like now just use a datatable - https://www.npmjs.com/package/react-data-table-component
- [ ] Altitude visualization component
  A visualization that will have the altitude as the Y axis and length in time in X axis - found a cool youtube here..
  https://www.youtube.com/watch?v=NlBt-7PuaLk
