### ISSUE TITLE
add request react component

### ISSUE THREAD

**Issue by liorkesos** [linnovate/dfa#4]
create add request component

**Comment by donno2048** [comment]
Already exists
 - [RequestSendAndEdit.tsx](https://github.com/linnovate/dfa/blob/main/ui/src/components/RequestSendAndEdit.tsx) for creating new requests
 - [Requests.tsx](https://github.com/linnovate/dfa/blob/main/ui/src/components/Requests.tsx) for viewing old requests

**Comment by liorkesos** [comment]
Current Ui in requests is not optimal for the content type.
- [ ] Time is actually 2 timedata fields that can be best visualized as a time/data picker
there is a list here for examples - https://blog.bitsrc.io/13-react-time-and-date-pickers-for-2020-d52d88d1ca0b
 - [ ] Coordinates should be a map picker - https://github.com/cyphercodes/location-picker/
 - [ ] Altitude should be a select list of heights in 100m  intervals (100,200,300 ... ) maybe until 2000m

**Comment by galronen211** [comment]
All requirements are met in DamlLogic branch.
